name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --prune --unshallow
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Pack 
      run: dotnet pack --no-build -c Release Rido.DeviceClientFactory/Rido.DeviceClientFactory.csproj
    
    - name: Add private GitHub registry to NuGet
      run: dotnet nuget add source https://nuget.pkg.github.com/ridomin/index.json -n GPR -u ridomin -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      
    - name: Push generated package to GitHub registry
      run: |
        for f in Rido.DeviceClientFactory/bin/Release/*.nupkg
        do
          dotnet nuget push $f --source "GPR" --skip-duplicate
        done

        for f in Rido.DeviceClientFactory/bin/Release/*.snupkg
        do
          dotnet nuget push $f --source "GPR" --skip-duplicate
        done
      shell: bash