name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Pack 
      run: dotnet pack --no-build -c Release Rido.DeviceClientFactory/Rido.DeviceClientFactory.csproj
    - id: FindNupkgs
      run: echo "::set-output name=file::$(ls Rido.DeviceClientFactory/bin/Release/*.*nupkg)"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NuPkgs
        path: ${{ steps.FindNupkgs.outputs.file }}
